[package]
name = "chat-completions-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "completions-chat"
path = "src/completions-chat.rs"

[[bin]]
name = "completions-streaming"
path = "src/completions-streaming.rs"

[dependencies]
openai-rust = { path = "../../openai-rust" }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
tokio-stream = "0.1"
futures = "0.3"
